name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      pgtest:
        image: postgres:16
        env:
          POSTGRES_USER: "cl-user"
          POSTGRES_PASSWORD: "cl-user-password"
          POSTGRES_DB: "rbac"
        ports:
          - "5433:5432"
        volumes:
          - "${{ github.workspace }}/src/init.sql:/docker-entrypoint-initdb.d/init.sql"
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 10s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache system packages
        id: cache-apt
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: automake build-essential curl git gnupg libcurl4-openssl-dev zlib1g-dev
          version: 1.0

      - name: Set up PATH
        run: |
          echo "PATH=/roswell/bin:$PATH" >> $GITHUB_ENV

      - name: Cache Roswell
        id: cache-dependencies
        uses: actions/cache@v4
        with:
          path: |
            /roswell/bin/ros
            /roswell/etc/roswell
            ~/.roswell
            ~/.cache
          key: ${{ runner.os }}-roswell-24

      - name: Verify Roswell paths
        run: |
          if command -v ros >/dev/null 2>&1; then
            echo "Roswell found at $(which ros)"
          else
            echo "Roswell not found"
          fi

      - name: Run setup and tests
        run: |
          # Only run full setup if cache was not hit
          if command -v ros >/dev/null 2>&1; then
            echo "Cache hit, skipping Roswell installation"
          else
            echo "Cache miss, running full setup"
            make -f .github/workflows/Makefile setup
          fi
          make -f .github/workflows/Makefile test
